# Vagrantfile
VAGRANTFILE_API_VERSION = "2"

NODES = [
  { :hostname => "master-1", :ip => "192.168.56.11" },
  { :hostname => "master-2", :ip => "192.168.56.12" },
  { :hostname => "master-3", :ip => "192.168.56.13" },
  { :hostname => "worker-1", :ip => "192.168.56.21" },
  { :hostname => "worker-2", :ip => "192.168.56.22" },
  { :hostname => "worker-3", :ip => "192.168.56.23" }
]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/jammy64"

  NODES.each do |node|
    config.vm.define node[:hostname] do |node_config|
      node_config.vm.hostname = node[:hostname]
      node_config.vm.network "private_network", ip: node[:ip]
      node_config.vm.provider "virtualbox" do |vb|
        vb.name = node[:hostname]
        vb.memory = 2048
        vb.cpus = 2
      end

      node_config.vm.provision "shell", inline: <<-SHELL
        apt-get update -y
        apt-get install -y python3 python3-pip
      SHELL
    end
  end
end
